version: "3.9"
services:
  redis:
    image: redis:7-alpine
    ports: ["6379:6379"]
  api:
    build: ./
    environment:
      NODE_ENV: production
      PORT: 8787
      NASA_API_KEY: ${NASA_API_KEY}
      ALLOWED_ORIGINS: http://localhost:5173
      REDIS_URL: redis://redis:6379
      CACHE_TTL_SECONDS: 900
      LOG_LEVEL: info
    depends_on: [redis]
    ports: ["8787:8787"]
